language: python

python:
  - '3.6'

addons:
  chrome: stable
  firefox: "73.0"
  apt:
    packages:
      firefox-geckodriver

branches:
  only:
    - profile
    - save
    - fixture
    - forgot-password
    - test-selenium
    - redirection

before_install:
  - wget https://chromedriver.storage.googleapis.com/80.0.3987.16/chromedriver_linux64.zip
  - sudo unzip chromedriver_linux64.zip -d /usr/bin/chromedriver
  - export PATH="$PATH:/usr/bin/chromedriver"
  - export DJANGO_SETTINGS_MODULE="purbeurre.travis"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - pip install -r requirements.txt

env:
  - MOZ_HEADLESS=1

services:
  - postgresql

script:
  - ./manage.py migrate
  - ./manage.py test
  