language: python

python:
  - '3.6'

branches:
  only:
    - profile
    - save
    - fixture


before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="purbeurre.travis"

services:
  - postgresql

script:
  - ./manage.py migrate
  - ./manage.py test
