# Generated by Django 2.2.8 on 2020-02-05 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Catégorie',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, unique=True, verbose_name='Level')),
            ],
            options={
                'verbose_name': 'Level',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du produit')),
                ('nutriscore', models.CharField(max_length=1, verbose_name='Nutriscore')),
                ('url', models.URLField(unique=True, verbose_name='URL')),
                ('photo', models.URLField(verbose_name='Photo')),
                ('fat_100g', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('sugars_100g', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('salt_100g', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('saturate_fat_100g', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='product.Category', verbose_name='Catégorie ID')),
                ('level_fat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levelFat', to='product.Level')),
                ('level_salt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levelSalt', to='product.Level')),
                ('level_saturate_fat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levelSaturateFat', to='product.Level')),
                ('level_sugars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levelSugars', to='product.Level')),
            ],
            options={
                'verbose_name': 'Produit',
            },
        ),
        migrations.CreateModel(
            name='Substitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.Product')),
                ('substitute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute', to='product.Product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favoris',
                'verbose_name_plural': 'Favoris',
            },
        ),
        migrations.AddConstraint(
            model_name='substitute',
            constraint=models.UniqueConstraint(fields=('product_id', 'substitute_id', 'user_id'), name='unique_relation'),
        ),
    ]
